### ISSUE TITLE
Apple M1 Support

### ISSUE THREAD

**Issue by duganth** [joschi/asdf-mvnd#1]
When trying to install latest version with plugin I receive: 
`asdf-mvnd error:  Unsupported architecture`

**Comment by joschi** [comment]
@duganth `mvnd` (as of version 0.4.1) only supports x86_64 but not ARM (aarch64).

What would be your expectation in this case? Should we install the x86_64 version on Macs with M1 processor to be used with Rosetta?

**Comment by joschi** [comment]
@duganth Is this still relevant for you?

**Comment by bskarda** [comment]
I opened up https://github.com/joschi/asdf-mvnd/pull/3 to add a fallback on m1 macs. Happy to tweak it.

If you want to try it out locally

```bash
asdf plugin add mvnd-m1 https://github.com/bskarda/asdf-mvnd.git
echo 'mvnd-m1' >> .tool-versions
asdf install
# use mvnd 
asdf plugin remove mvnd-m1
```
